### ISSUE TITLE
Willing to pay to support Ajax functions

### ISSUE THREAD

**Issue by kenfu** [bootsz/wp-advanced-search#120]
I bought a paid plugin, name search - filter - pro, but feel bad, until I met wp-advanced-search
， very excited.

If you can add these three function, increase the PRO version, better use the theme function.
1.Search results using Ajax function real-time refresh, don't have to click on the search button。
2.Have a more detailed tutorial and examples, combining wppostviews and wppostrating plug-ins, and display the form of custom more rob, showing separately.
3.By using the bootstrap, make the UI more beautiful.

PS：MORE LIKE  http://www.designsandcode.com/wordpress-plugins/search-filter-pro/
Looking forward to more rich functions, PRO version.

**Comment by bootsz** [comment]
Good news: Ajax will be supported in the next release (1.4).  I will try to do more tutorials if time permits.

Regarding Bootstrap, I do not plan to integrate it or any CSS whatsoever because in my view that is outside the scope of what this plugin is about.  I want to keep things flexible enough for each developer to style the forms how he/she chooses.
